// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH2xzc8S3j6TwsokoDjA4iIcn52BzK3wo',
    appId: '1:145122252238:web:bb3f0638a2da379f92479f',
    messagingSenderId: '145122252238',
    projectId: 'salam-school-e49c5',
    authDomain: 'salam-school-e49c5.firebaseapp.com',
    storageBucket: 'salam-school-e49c5.appspot.com',
    measurementId: 'G-WNQVYE74MC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAK6k2bhVoA1XlzsXxS9mwdtdw6ZEPDpNE',
    appId: '1:145122252238:android:29072d04c26af9f592479f',
    messagingSenderId: '145122252238',
    projectId: 'salam-school-e49c5',
    storageBucket: 'salam-school-e49c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDoPsiJDbrkINDh64XEuAn7ZMil0CxsniE',
    appId: '1:145122252238:ios:cb48d80a492292f892479f',
    messagingSenderId: '145122252238',
    projectId: 'salam-school-e49c5',
    storageBucket: 'salam-school-e49c5.appspot.com',
    iosBundleId: 'com.example.salamSchool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDoPsiJDbrkINDh64XEuAn7ZMil0CxsniE',
    appId: '1:145122252238:ios:cb48d80a492292f892479f',
    messagingSenderId: '145122252238',
    projectId: 'salam-school-e49c5',
    storageBucket: 'salam-school-e49c5.appspot.com',
    iosBundleId: 'com.example.salamSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDH2xzc8S3j6TwsokoDjA4iIcn52BzK3wo',
    appId: '1:145122252238:web:7bcfe38542f88b4e92479f',
    messagingSenderId: '145122252238',
    projectId: 'salam-school-e49c5',
    authDomain: 'salam-school-e49c5.firebaseapp.com',
    storageBucket: 'salam-school-e49c5.appspot.com',
    measurementId: 'G-MSFN84P031',
  );
}
